### PR TITLE
Dj/open on colon

### PR DESCRIPTION
**Pull request by dylanjha**
## TODO
- [ ] make open on colon implementation work on content-editable fields

Thanks for building and maintaining this library @needim .

I added a few things:
## 1. Documentation in README
- most of this is copy/pasted from the demo)
## 2. Expose `afterSelected` event
- the public interface to register this listener was already there, I simply fired the event at the right time
## 3. Add (optional) slack-like functionality to open the picker when a user types `:` followed by 2 non-space characters
- The way to do this is to add the class `wdt-emoji-open-on-colon` to the input that is getting the emoji picker applied to it
- This currently only works on `input` it doesn't work on content-editable elements (this functionality can be added before merging)
- See demo here: https://dylanjha.github.io/wdt-emoji-bundle/demo/ (scroll down to the Open on Colon section)

emoji-colon

If you like these changes I'm happy to add the colon functionality to contenteditable elements, rebase, clean up the commit history and get it merged in to the source. Please let me know! 🍻

### CODE REVIEW

**Comment by needim** [comment]
Wow cool pr thanks @dylanjha. 👍  I will test this. Sorry for the late response.

**Comment by dylanjha** [comment]
@needim I will likely need to revisit this to get it mergable. Are you interested in getting this functionality into the library?

**Comment by needim** [comment]
@dylanjha Yep sure.

**Comment by dylanjha** [comment]
@needim did you test this out before merging?

**Comment by needim** [comment]
Nope 😄  But I'm testing now and it's working good right now 😄  I'm planning a release soon, thanks again for the feature. 😉

**Pull request merged**
